import { Router, type IRouter } from "express";
import healthRouter from "./health";
import liveRouter from "./live";
import clubRouter from "./club";
import athletesRouter from "./athletes";
import teamsRouter from "./teams";
import meetsRouter from "./meets";
import sessionsRouter from "./sessions";
import eventsRouter from "./events";
import entriesRouter from "./entries";
import heatsRouter from "./heats";
import resultsRouter from "./results";
import relaysRouter from "./relays";
import timeStandardsRouter from "./timestandards";
import workoutsRouter from "./workouts";
import billingRouter from "./billing";
import dashboardRouter from "./dashboard";
import reportsRouter from "./reports";
import sdifRouter from "./sdif";
import officialsRouter from "./officials";
import recordsRouter from "./records";
import groupsRouter from "./groups";
import attendanceRouter from "./attendance";
import backupRouter from "./backup";

const router: IRouter = Router();

router.use(healthRouter);
router.use(liveRouter);
router.use(clubRouter);
router.use(athletesRouter);
router.use(teamsRouter);
router.use(meetsRouter);
router.use(sessionsRouter);
router.use(eventsRouter);
router.use(entriesRouter);
router.use(heatsRouter);
router.use(resultsRouter);
router.use(relaysRouter);
router.use(timeStandardsRouter);
router.use(workoutsRouter);
router.use(billingRouter);
router.use(dashboardRouter);
router.use(reportsRouter);
router.use(sdifRouter);
router.use(officialsRouter);
router.use(recordsRouter);
router.use(groupsRouter);
router.use(attendanceRouter);
router.use(backupRouter);

export default router;
